### ISSUE TITLE
[javascript] $let leaks assignments

### ISSUE THREAD

**Issue by tadpol** [json-e/json-e#473] opened 2023-10-17 20:54 UTC
Given a template:
```yaml
- $let:
    outlets: [1,2,3]
  in: {$eval: "outlets"}
- {$eval: "outlets"}
```

I would expect the results to be:
```yaml
# Error:
# InterpreterError at template[1]: unknown context value outlets
```

Instead it is:
```yaml
- &ref_0
  - 1
  - 2
  - 3
- *ref_0
```

Above tested with the online playground.  I also tested it in python, which does the correct thing:
```python
>>> import jsone
>>> context={}
>>> template= [ { "$let": { "outlets": [1,2,3] }, "in": { "$eval": "outlets" } }, {"$eval": "outlets"} ]
>>> print(jsone.render(template, context))                                                           Traceback (most recent call last):
  File "/Users/miketilstra/Downloads/json-e-test/lib/python3.11/site-packages/jsone/interpreter.py", line 164, in visit_ContextValue
    contextValue = self.context[node.token.value]
                   ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'outlets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/miketilstra/Downloads/json-e-test/lib/python3.11/site-packages/jsone/__init__.py", line 20, in render
    rv = renderValue(template, full_context)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/miketilstra/Downloads/json-e-test/lib/python3.11/site-packages/jsone/render.py", line 447, in renderValue
    return list(updated())
           ^^^^^^^^^^^^^^^
  File "/Users/miketilstra/Downloads/json-e-test/lib/python3.11/site-packages/jsone/render.py", line 440, in updated
    v = renderValue(e, context)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/miketilstra/Downloads/json-e-test/lib/python3.11/site-packages/jsone/render.py", line 412, in renderValue
    return operators[matches[0]](template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/miketilstra/Downloads/json-e-test/lib/python3.11/site-packages/jsone/render.py", line 122, in eval
    return parse(template['$eval'], context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/miketilstra/Downloads/json-e-test/lib/python3.11/site-packages/jsone/render.py", line 59, in parse
    result = interp.interpret(tree)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/miketilstra/Downloads/json-e-test/lib/python3.11/site-packages/jsone/interpreter.py", line 192, in interpret
    return self.visit(tree)
           ^^^^^^^^^^^^^^^^
  File "/Users/miketilstra/Downloads/json-e-test/lib/python3.11/site-packages/jsone/interpreter.py", line 17, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/Users/miketilstra/Downloads/json-e-test/lib/python3.11/site-packages/jsone/interpreter.py", line 166, in visit_ContextValue
    raise InterpreterError(
jsone.shared.InterpreterError: InterpreterError at template[1]: unknown context value outlets
```

**Comment by djmitche** [comment] 2023-10-26 22:54
This sounds like an interesting bug -- good find!

Were you able to track down the cause or a fix?

**Comment by tadpol** [comment] 2023-10-27 00:12
Only partially. It looks like there is a call to `Object.assign()` with current context as the first parameter, and it probably should have a new empty object there instead.  At [/js/src/index.js#L168](https://github.com/json-e/json-e/blob/2fbb81ab06d2995a9dda33092fc186f798926584/js/src/index.js#L168)   So maybe a `var child_context = Object.assign({}, context, variables);` instead?  I haven't had time to try it out and see if that breaks anything else.

**Comment by djmitche** [comment] 2023-10-29 17:23
I'll assign this to you for the moment in case you have some time -- no rush. If you think you won't be able to finish, let me know and I can reassign.

**Closed** 2023-11-04 01:00 UTC
